ALTER TABLE DOKUMENTKATALOG ADD (
	ikke_redigerbar_mal_id VARCHAR2(20) NULL,
	redigerbar_mal_id VARCHAR2(20) NULL
);

UPDATE DOKUMENTKATALOG
SET REDIGERBAR_MAL_ID = MAL_ID
WHERE REDIGERBART = 'T';

UPDATE DOKUMENTKATALOG
SET IKKE_REDIGERBAR_MAL_ID = MAL_ID
WHERE REDIGERBART = 'F';
