-- This is temporary until we can get automatic maldeploy up and running

INSERT INTO DOKUMENTKATALOG (dokumentkatalog_id, dokumenttype_id, mal_id, mal_logikk_fil, mal_version, mal_xsd_referanse, dokument_kategori, sensitivt, portoklasse, opprettet_dato, opprettet_av, endret_dato, endret_av, versjon, dokument_tittel, redigerbart, vedlegg) VALUES (1, '000001', '000001', 'Arena', '1.0.0', 'xsdfileshare/Arena/Allow_Any_All.xsd', 'B', 'F', 'A', current_timestamp, 'J. Bjørnstad', null, null, 1, 'Innkalling til gruppeaktivitet', 'F', 'F');
INSERT INTO DOKUMENTKATALOG (dokumentkatalog_id, dokumenttype_id, mal_id, mal_logikk_fil, mal_version, mal_xsd_referanse, dokument_kategori, sensitivt, portoklasse, opprettet_dato, opprettet_av, endret_dato, endret_av, versjon, dokument_tittel, redigerbart, vedlegg) VALUES (2, '000002', '000002', 'Arena', '1.0.0', 'xsdfileshare/Arena/Allow_Any_All.xsd', 'B', 'F', 'A', current_timestamp, 'J. Bjørnstad', null, null, 1, 'Individuell innkalling', 'T', 'F');
INSERT INTO DOKUMENTKATALOG (dokumentkatalog_id, dokumenttype_id, mal_id, mal_logikk_fil, mal_version, mal_xsd_referanse, dokument_kategori, sensitivt, portoklasse, opprettet_dato, opprettet_av, endret_dato, endret_av, versjon, dokument_tittel, redigerbart, vedlegg) VALUES (4, '000007', '000007', 'Arena', '1.0.0', 'xsdfileshare/Arena/Allow_Any_All.xsd', 'B', 'F', 'A', current_timestamp, 'J. Bjørnstad', null, null, 1, 'Forhåndsvarsel', 'F', 'F');
INSERT INTO DOKUMENTKATALOG (dokumentkatalog_id, dokumenttype_id, mal_id, mal_logikk_fil, mal_version, mal_xsd_referanse, dokument_kategori, sensitivt, portoklasse, opprettet_dato, opprettet_av, endret_dato, endret_av, versjon, dokument_tittel, redigerbart, vedlegg) VALUES (5, '000008', '000008', 'Arena', '1.0.0', 'xsdfileshare/Arena/Allow_Any_All.xsd', 'B', 'F', 'A', current_timestamp, 'J. Bjørnstad', null, null, 1, 'Mangelbrev', 'F', 'F');
INSERT INTO DOKUMENTKATALOG (dokumentkatalog_id, dokumenttype_id, mal_id, mal_logikk_fil, mal_version, mal_xsd_referanse, dokument_kategori, sensitivt, portoklasse, opprettet_dato, opprettet_av, endret_dato, endret_av, versjon, dokument_tittel, redigerbart, vedlegg) VALUES (3, '000009', '000009', 'Arena', '1.0.0', 'xsdfileshare/Arena/Allow_Any_All.xsd', 'B', 'F', 'A', current_timestamp, 'J. Bjørnstad', null, null, 1, 'Enkel forvaltningsmelding', 'F', 'F');
SELECT DOKUMENTKATALOG_SEQ.nextval from dual;
SELECT DOKUMENTKATALOG_SEQ.nextval from dual;
SELECT DOKUMENTKATALOG_SEQ.nextval from dual;
SELECT DOKUMENTKATALOG_SEQ.nextval from dual;
SELECT DOKUMENTKATALOG_SEQ.nextval from dual;
