ALTER TABLE DOKUMENTTYPE_INFO ADD K_PREDEFINERT_ARKIV_SYSTEM VARCHAR2(50 CHAR) DEFAULT 'JOARK' NOT NULL;

ALTER TABLE DOKUMENTTYPE_INFO
  ADD CONSTRAINT FK_ARKIVSYSTEM
FOREIGN KEY (K_PREDEFINERT_ARKIV_SYSTEM)
REFERENCES K_ARKIV_SYSTEM;

INSERT INTO K_ARKIV_SYSTEM VALUES ('INGEN', 'Ingen', TIMESTAMP '2018-04-19 10:00:00','Ragne Henriksen', null, null);

ALTER TABLE DOKUMENT_MOTTAK_INFO
  DROP COLUMN K_PREDEFINERT_ARKIV_SYSTEM;



