INSERT INTO K_DIST_KANAL (K_DIST_KANAL, DEKODE, OPPRETTET_AV, OPPRETTET_DATO)
SELECT 'TRYGDERETTEN', 'Trygderetten', 'Erik Braten', timestamp '2019-06-04 14:00:00'
FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM K_DIST_KANAL WHERE K_DIST_KANAL = 'TRYGDERETTEN');
