CREATE SEQUENCE XSD_FIL_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;

CREATE TABLE XSD_FIL
(
    ID NUMBER NOT NULL,
    BREVPAKKE VARCHAR2(128) NOT NULL,
    FILSTI VARCHAR2(512) NOT NULL,
    FILNAVN VARCHAR2(128) NOT NULL,
    XSDFIL BLOB NOT NULL
);