ALTER TABLE DOKUMENT_MOTTAK_INFO DROP CONSTRAINT FK_ARKIV_BEHANDLING;
ALTER TABLE DOKUMENT_MOTTAK_INFO DROP COLUMN K_ARKIV_BEHANDLING;

DROP TABLE K_ARKIV_BEHANDLING;

ALTER TABLE DOKUMENT_MOTTAK_INFO DROP CONSTRAINT FK_KONV_BEHANDLING;
ALTER TABLE DOKUMENT_MOTTAK_INFO DROP COLUMN K_KONV_BEHANDLING;

DROP TABLE K_KONV_BEHANDLING;