DROP TABLE DOKUMENTKATALOG;
DROP SEQUENCE DOKUMENTKATALOG_SEQ;

CREATE TABLE DOKUMENTTYPE_INFO
(
  ID                      NUMBER(19, 0)      NOT NULL,
  DOKUMENTTYPE_ID         VARCHAR2(20 CHAR)  NOT NULL,
  DOKUMENT_TITTEL         VARCHAR2(200 CHAR) NOT NULL,
  VEDLEGG                 NUMBER(1, 0)       NOT NULL,
  EKSTERN_VEDLEGG         NUMBER(1, 0)       NOT NULL,
  IKKE_REDIGERBAR_MAL_ID  VARCHAR2(20 CHAR)  NULL,
  REDIGERBAR_MAL_ID       VARCHAR2(20 CHAR)  NULL,
  MAL_LOGIKK_FIL          VARCHAR2(50 CHAR)  NOT NULL,
  MAL_XSD_REFERANSE       VARCHAR2(200 CHAR) NOT NULL,
  MAL_VERSION             VARCHAR2(40 CHAR)  NOT NULL,
  DOKUMENT_KATEGORI       VARCHAR2(50 CHAR)  NOT NULL,
  SENSITIVT               NUMBER(1, 0)       NOT NULL,
  FK_DISTRIBUSJON_INFO_ID NUMBER(19, 0)      NULL,
  OPPRETTET_AV            VARCHAR2(50 CHAR)  NOT NULL,
  OPPRETTET_DATO          TIMESTAMP          NOT NULL,
  ENDRET_AV               VARCHAR2(50 CHAR)  NULL,
  ENDRET_DATO             TIMESTAMP          NULL,
  VERSJON                 NUMBER(19, 0)      NOT NULL,
  CONSTRAINT XPK_DOKUMENTTYPE_INFO PRIMARY KEY (ID)
);

CREATE TABLE DISTRIBUSJON_INFO
(
  ID                       NUMBER(19, 0)     NOT NULL,
  K_PREDEFINERT_DIST_KANAL VARCHAR2(50 CHAR) NULL,
  PORTOKLASSE              VARCHAR2(20 CHAR) NOT NULL,
  SIKKERHETSNIVAA          NUMBER(2)         NOT NULL,
  OPPRETTET_AV             VARCHAR2(50 CHAR) NOT NULL,
  OPPRETTET_DATO           TIMESTAMP         NOT NULL,
  ENDRET_AV                VARCHAR2(50 CHAR) NULL,
  ENDRET_DATO              TIMESTAMP         NULL,
  VERSJON                  NUMBER(19, 0)     NOT NULL,
  CONSTRAINT XPK_DISTRIBUSJON_INFO PRIMARY KEY (ID)
);

CREATE TABLE DISTRIBUSJON_VARSEL
(
  ID                      NUMBER(19, 0)     NOT NULL,
  FK_DISTRIBUSJON_INFO_ID NUMBER(19, 0)     NOT NULL,
  K_VARSEL_FOR_DIST_KANAL VARCHAR2(50 CHAR) NOT NULL,
  VARSELTYPE_ID           VARCHAR2(50 CHAR) NOT NULL,
  OPPRETTET_AV            VARCHAR2(50 CHAR) NOT NULL,
  OPPRETTET_DATO          TIMESTAMP         NOT NULL,
  ENDRET_AV               VARCHAR2(50 CHAR) NULL,
  ENDRET_DATO             TIMESTAMP         NULL,
  VERSJON                 NUMBER(19, 0)     NOT NULL,
  CONSTRAINT XPK_DISTRIBUSJON_VARSEL PRIMARY KEY (ID)
);

CREATE TABLE VARSEL_INFO
(
  ID                      NUMBER(19, 0)     NOT NULL,
  VARSELTYPE_ID           VARCHAR2(50 CHAR) NOT NULL,
  VARSEL_KATEGORI         VARCHAR2(50 CHAR) NOT NULL,
  K_VARSEL_FOR_DIST_KANAL VARCHAR2(50 CHAR) NULL,
  INAKTIV                 NUMBER(1, 0)      NOT NULL,
  REVARSLING_INTERVALL    NUMBER(10, 0)     NULL,
  ANTALL_REVARSLINGER     NUMBER(10, 0)     NULL,
  MAL_VERSION             VARCHAR2(40 CHAR) NOT NULL,
  OPPRETTET_AV            VARCHAR2(50 CHAR) NOT NULL,
  OPPRETTET_DATO          TIMESTAMP         NOT NULL,
  ENDRET_AV               VARCHAR2(50 CHAR) NULL,
  ENDRET_DATO             TIMESTAMP         NULL,
  VERSJON                 NUMBER(19, 0)     NOT NULL,
  CONSTRAINT XPK_VARSEL_INFO PRIMARY KEY (ID)
);

CREATE TABLE VARSEL_MAL
(
  ID                       NUMBER(19, 0)       NOT NULL,
  FK_VARSEL_INFO_ID        NUMBER(19, 0)       NOT NULL,
  K_KANAL                  VARCHAR2(20 CHAR)   NOT NULL,
  VARSEL_TITTEL            VARCHAR2(255 CHAR)  NULL,
  FOERSTEGANGSVARSEL_TEKST VARCHAR2(1000 CHAR) NOT NULL,
  REVARSLING_TEKST         VARCHAR2(1000 CHAR) NULL,
  OPPRETTET_AV             VARCHAR2(50 CHAR)   NOT NULL,
  OPPRETTET_DATO           TIMESTAMP           NOT NULL,
  ENDRET_AV                VARCHAR2(50 CHAR)   NULL,
  ENDRET_DATO              TIMESTAMP           NULL,
  VERSJON                  NUMBER(19, 0)       NOT NULL,
  CONSTRAINT XPK_VARSEL_MAL PRIMARY KEY (ID)
);

CREATE TABLE K_KANAL (
  K_KANAL        VARCHAR2(20 CHAR)  NOT NULL,
  DEKODE         VARCHAR2(200 CHAR) NOT NULL,
  OPPRETTET_DATO TIMESTAMP          NOT NULL,
  OPPRETTET_AV   VARCHAR2(50 CHAR)  NOT NULL,
  ENDRET_DATO    TIMESTAMP          NULL,
  ENDRET_AV      VARCHAR2(50 CHAR)  NULL,
  CONSTRAINT XPK_KANAL PRIMARY KEY (K_KANAL)
);

CREATE TABLE K_DIST_KANAL (
  K_DIST_KANAL   VARCHAR2(50 CHAR)  NOT NULL,
  DEKODE         VARCHAR2(200 CHAR) NOT NULL,
  OPPRETTET_DATO TIMESTAMP          NOT NULL,
  OPPRETTET_AV   VARCHAR2(50 CHAR)  NOT NULL,
  ENDRET_DATO    TIMESTAMP          NULL,
  ENDRET_AV      VARCHAR2(50 CHAR)  NULL,
  CONSTRAINT XPK_DISTKANAL PRIMARY KEY (K_DIST_KANAL)
);

CREATE TABLE VARSEL_INFO_PREFKANAL (
  FK_VARSEL_INFO_ID NUMBER(19, 0)     NOT NULL,
  K_KANAL           VARCHAR2(20 CHAR) NOT NULL,
  CONSTRAINT XPK_PREFKANAL PRIMARY KEY (FK_VARSEL_INFO_ID, K_KANAL)
);

CREATE UNIQUE INDEX XAK1DOKUMENTTYPE_INFO ON DOKUMENTTYPE_INFO
(DOKUMENTTYPE_ID ASC);

CREATE INDEX XAK2DOKUMENTTYPE_INFO ON DOKUMENTTYPE_INFO
(MAL_LOGIKK_FIL ASC);

-- must create index first, as creating a constraint will implicitly create an index.
-- yet oracle strongly recommends that you explicitly create an index if you need it for performance.
CREATE UNIQUE INDEX XAK1VARSEL_INFO ON VARSEL_INFO
(VARSELTYPE_ID ASC);

ALTER TABLE VARSEL_INFO
  ADD CONSTRAINT UK_VARSELTYPE_ID UNIQUE (VARSELTYPE_ID);

CREATE SEQUENCE DOKUMENTTYPE_INFO_SEQ START WITH 100 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE DISTRIBUSJON_INFO_SEQ START WITH 100 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE DISTRIBUSJON_VARSEL_SEQ START WITH 100 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE VARSEL_INFO_SEQ START WITH 100 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE VARSEL_MAL_SEQ START WITH 100 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;

ALTER TABLE DISTRIBUSJON_INFO
  ADD CONSTRAINT FK_DISTINF_DISTKANAL
FOREIGN KEY (K_PREDEFINERT_DIST_KANAL)
REFERENCES K_DIST_KANAL;

ALTER TABLE DISTRIBUSJON_VARSEL
  ADD CONSTRAINT FK_DISTVAR_DISTKANAL
FOREIGN KEY (K_VARSEL_FOR_DIST_KANAL)
REFERENCES K_DIST_KANAL;

ALTER TABLE VARSEL_INFO_PREFKANAL
  ADD CONSTRAINT FK_VARSINFPKAN_VARSINF
FOREIGN KEY (FK_VARSEL_INFO_ID)
REFERENCES VARSEL_INFO;

ALTER TABLE VARSEL_INFO_PREFKANAL
  ADD CONSTRAINT FK_VARSINFPKAN_KANAL
FOREIGN KEY (K_KANAL)
REFERENCES K_KANAL;

ALTER TABLE VARSEL_INFO
  ADD CONSTRAINT FK_VARSINF_DISTKANAL
FOREIGN KEY (K_VARSEL_FOR_DIST_KANAL)
REFERENCES K_DIST_KANAL;

ALTER TABLE VARSEL_MAL
  ADD CONSTRAINT FK_VARSMAL_KANAL
FOREIGN KEY (K_KANAL)
REFERENCES K_KANAL;

ALTER TABLE DISTRIBUSJON_VARSEL
  ADD CONSTRAINT FK_DISTVARS_VARSINFO
FOREIGN KEY (VARSELTYPE_ID)
REFERENCES VARSEL_INFO (VARSELTYPE_ID);
