INSERT INTO K_KANAL (K_KANAL, DEKODE, OPPRETTET_AV, OPPRETTET_DATO)
VALUES ('SMS', 'SMS Melding', 'Gerhard Wiese', TIMESTAMP '2016-05-19 10:00:00');
INSERT INTO K_KANAL (K_KANAL, DEKODE, OPPRETTET_AV, OPPRETTET_DATO)
VALUES ('EPOST', 'E-post', 'Gerhard Wiese', TIMESTAMP '2016-05-19 10:00:00');
INSERT INTO K_KANAL (K_KANAL, DEKODE, OPPRETTET_AV, OPPRETTET_DATO)
VALUES ('DITT_NAV', 'Ditt Nav', 'Gerhard Wiese', TIMESTAMP '2016-05-19 10:00:00');

INSERT INTO K_DIST_KANAL (K_DIST_KANAL, DEKODE, OPPRETTET_AV, OPPRETTET_DATO)
VALUES ('SDP', 'Sikker Digital Post', 'Thomas Fiksdal', TIMESTAMP '2016-06-09 10:00:00');
INSERT INTO K_DIST_KANAL (K_DIST_KANAL, DEKODE, OPPRETTET_AV, OPPRETTET_DATO)
VALUES ('DITT_NAV', 'Ditt Nav', 'Thomas Fiksdal', TIMESTAMP '2016-06-09 10:00:00');
INSERT INTO K_DIST_KANAL (K_DIST_KANAL, DEKODE, OPPRETTET_AV, OPPRETTET_DATO)
VALUES ('SENTRAL_PRINT', 'Sentral Print', 'Thomas Fiksdal', TIMESTAMP '2016-06-09 10:00:00');
INSERT INTO K_DIST_KANAL (K_DIST_KANAL, DEKODE, OPPRETTET_AV, OPPRETTET_DATO)
VALUES ('LOKAL_PRINT', 'Lokal Print', 'Thomas Fiksdal', TIMESTAMP '2016-06-09 10:00:00');
INSERT INTO K_DIST_KANAL (K_DIST_KANAL, DEKODE, OPPRETTET_AV, OPPRETTET_DATO)
VALUES ('VED_DITT_NAV_OGSA_PRINT', 'Hvis Ditt Nav også send Print', 'Thomas Fiksdal', TIMESTAMP '2016-06-09 10:00:00');