CREATE TABLE K_VARSEL_KATEGORI (
  K_VARSEL_KATEGORI VARCHAR2(50 CHAR)  NOT NULL,
  DEKODE            VARCHAR2(200 CHAR) NOT NULL,
  OPPRETTET_DATO    TIMESTAMP          NOT NULL,
  OPPRETTET_AV      VARCHAR2(50 CHAR)  NOT NULL,
  ENDRET_DATO       TIMESTAMP          NULL,
  ENDRET_AV         VARCHAR2(50 CHAR)  NULL,
  CONSTRAINT XPK_VARSELKAT PRIMARY KEY (K_VARSEL_KATEGORI)
);

INSERT INTO K_VARSEL_KATEGORI (K_VARSEL_KATEGORI, DEKODE, OPPRETTET_AV, OPPRETTET_DATO)
VALUES ('DISTRIBUSJON', 'Varsel for distribusjon av dokument', 'Andreas Skomedal', TIMESTAMP '2016-08-12 10:00:00');
INSERT INTO K_VARSEL_KATEGORI (K_VARSEL_KATEGORI, DEKODE, OPPRETTET_AV, OPPRETTET_DATO)
VALUES ('SERVICEMELDING', 'Varsel av servicemelding', 'Andreas Skomedal', TIMESTAMP '2016-08-12 10:00:00');

ALTER TABLE VARSEL_INFO
  DROP COLUMN varsel_kategori;

ALTER TABLE VARSEL_INFO
  ADD K_VARSEL_KATEGORI VARCHAR2(50 CHAR);

ALTER TABLE VARSEL_INFO
  ADD CONSTRAINT FK_VARSINF_VARSKAT
FOREIGN KEY (K_VARSEL_KATEGORI)
REFERENCES K_VARSEL_KATEGORI;

-- Set default kategori for existing testdata, should not affect any rows in production or other clean environments
UPDATE VARSEL_INFO
SET K_VARSEL_KATEGORI = 'DISTRIBUSJON';

ALTER TABLE VARSEL_INFO
  MODIFY K_VARSEL_KATEGORI NOT NULL;
