-- backup eksisterende
CREATE TABLE BACKUP_DOKUMENTYPE_INFO AS SELECT * FROM DOKUMENTTYPE_INFO; 

CREATE TABLE FKV_DOKUMENTTITTEL 
(
	ID                      NUMBER(19, 0)      NOT NULL,
	VERSJONSNUMMER			VARCHAR2(20 CHAR)  NOT NULL,
	KODE					VARCHAR2(50 CHAR)  NOT NULL,
	KODE_GYLDIG_FRA         TIMESTAMP,
	KODE_GYLDIG_TIL         TIMESTAMP,
	TERM          			VARCHAR2(300 CHAR)  NOT NULL,
	TERM_GYLDIG_FRA         TIMESTAMP,
	TERM_GYLDIG_TIL         TIMESTAMP,	
	OPPRETTET_AV            VARCHAR2(50 CHAR)  NOT NULL,
	OPPRETTET_DATO          TIMESTAMP          NOT NULL,
	ENDRET_AV               VARCHAR2(50 CHAR)  NULL,
	ENDRET_DATO             TIMESTAMP          NULL,
	VERSJON                 NUMBER(19, 0)      NOT NULL,
	CONSTRAINT XPK_FKV_DOKUMENTTITTEL PRIMARY KEY (ID)
);

CREATE SEQUENCE FKV_DOKTITTEL_SEQ START WITH 100 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;

CREATE TABLE DOKUMENT_PRODUKSJON_INFO AS SELECT 
  ID, 
  VEDLEGG, 
  EKSTERN_VEDLEGG, 
  IKKE_REDIGERBAR_MAL_ID, 
  REDIGERBAR_MAL_ID,
  MAL_LOGIKK_FIL,
  MAL_XSD_REFERANSE,
  MAL_VERSION,
  FK_DISTRIBUSJON_INFO_ID,
  OPPRETTET_AV,
  OPPRETTET_DATO,
  ENDRET_AV,
  ENDRET_DATO,
  VERSJON 
FROM DOKUMENTTYPE_INFO;

ALTER TABLE DOKUMENT_PRODUKSJON_INFO 
	ADD CONSTRAINT XPK_DOKUMENTPROD_INFO PRIMARY KEY (ID);

ALTER TABLE DOKUMENTTYPE_INFO
	ADD (
    K_DOKUMENTTYPE VARCHAR2(50 CHAR)
);

CREATE TABLE K_DOKUMENTTYPE (
  K_DOKUMENTTYPE VARCHAR2(50 CHAR)  NOT NULL,
  DEKODE         VARCHAR2(200 CHAR) NOT NULL,
  OPPRETTET_DATO TIMESTAMP          NOT NULL,
  OPPRETTET_AV   VARCHAR2(50 CHAR)  NOT NULL,
  ENDRET_DATO    TIMESTAMP          NULL,
  ENDRET_AV      VARCHAR2(50 CHAR)  NULL,
  CONSTRAINT XPK_DOKUMENTTYPE PRIMARY KEY (K_DOKUMENTTYPE)
);

ALTER TABLE DOKUMENTTYPE_INFO
  ADD CONSTRAINT FK_DOKTYPEINFO_DOKTYPE
FOREIGN KEY (K_DOKUMENTTYPE)
REFERENCES K_DOKUMENTTYPE;

ALTER TABLE DOKUMENTTYPE_INFO 
	DROP(
		VEDLEGG, 
  		EKSTERN_VEDLEGG, 
  		IKKE_REDIGERBAR_MAL_ID, 
 		REDIGERBAR_MAL_ID,
  		MAL_LOGIKK_FIL,
  		MAL_XSD_REFERANSE,
  		MAL_VERSION,
  		FK_DISTRIBUSJON_INFO_ID
);

INSERT INTO K_DOKUMENTTYPE VALUES ('I', 'Inngående', TIMESTAMP '2017-01-10 10:00:00','Ragne Henriksen', null, null); 
INSERT INTO K_DOKUMENTTYPE VALUES ('U', 'Utgående', TIMESTAMP '2017-01-10 10:00:00','Ragne Henriksen', null, null); 
INSERT INTO K_DOKUMENTTYPE VALUES ('N', 'Notat', TIMESTAMP '2017-01-10 10:00:00','Ragne Henriksen', null, null); 

-- setter eksisterende dokumentype_info til Utgående
UPDATE DOKUMENTTYPE_INFO set K_DOKUMENTTYPE = 'U';

ALTER TABLE DOKUMENTTYPE_INFO MODIFY (K_DOKUMENTTYPE NOT NULL);