ALTER TABLE DOKUMENTTYPE_INFO
MODIFY (DOKUMENT_TITTEL NULL);

CREATE TABLE DOKUMENT_MOTTAK_INFO
(
	ID                      NUMBER(11)         NOT NULL ,
	PREDEFINERT_AVSENDER    VARCHAR2(20 CHAR)  NULL ,
	K_BEHANDLENDE_FAGSYSTEM VARCHAR2(20 CHAR)  NULL ,
	OPPRETTET_DATO          TIMESTAMP          NOT NULL ,
	OPPRETTET_AV            VARCHAR2(20 CHAR)  NOT NULL ,
	ENDRET_DATO             TIMESTAMP          NULL ,
	ENDRET_AV               VARCHAR2(20 CHAR)  NULL ,
	VERSJON                 NUMBER(9)          NOT NULL,
	CONSTRAINT XPK_DOKUMENTMOTTAK_INFO PRIMARY KEY (ID)
);

CREATE TABLE K_BEHANDLENDE_FAGSYSTEM
(
  K_BEHANDLENDE_FAGSYSTEM VARCHAR2(50 CHAR)  NOT NULL,
  DEKODE                  VARCHAR2(255 CHAR) NOT NULL,
  OPPRETTET_DATO          TIMESTAMP          NOT NULL,
  OPPRETTET_AV            VARCHAR2(20 CHAR) NOT NULL,
  ENDRET_DATO             TIMESTAMP          NULL,
  ENDRET_AV               VARCHAR2(20 CHAR) NULL,
  CONSTRAINT XPK_BEHANDLENDE_FAGSYSTEMKANAL PRIMARY KEY (K_BEHANDLENDE_FAGSYSTEM)
);

ALTER TABLE DOKUMENT_MOTTAK_INFO
  ADD CONSTRAINT FK_BFAGVAR_BFAGKANAL
FOREIGN KEY (K_BEHANDLENDE_FAGSYSTEM)
REFERENCES K_BEHANDLENDE_FAGSYSTEM;

ALTER TABLE DOKUMENT_MOTTAK_INFO
  ADD CONSTRAINT FK_DOKMTK_I_DOKTYP_I
FOREIGN KEY (ID)
REFERENCES DOKUMENTTYPE_INFO;

INSERT INTO K_BEHANDLENDE_FAGSYSTEM(K_BEHANDLENDE_FAGSYSTEM, DEKODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('AO01', 'Arena', TIMESTAMP '2017-01-10 10:00:00', 'Ragne Henriksen');
INSERT INTO K_BEHANDLENDE_FAGSYSTEM(K_BEHANDLENDE_FAGSYSTEM, DEKODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('IT01', 'Infotrygd', TIMESTAMP '2017-01-10 10:00:00', 'Ragne Henriksen');
INSERT INTO K_BEHANDLENDE_FAGSYSTEM(K_BEHANDLENDE_FAGSYSTEM, DEKODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('FS22', 'Gosys', TIMESTAMP '2017-01-10 10:00:00', 'Ragne Henriksen');