CREATE TABLE DOKKAT_STATE (
  DOKKAT_STATE_ID NUMBER(1, 0)        NOT NULL,
  LAST_MASTER_PING TIMESTAMP          NOT NULL,
  CURRENT_MASTER   VARCHAR2(255 CHAR) NOT NULL
);

ALTER TABLE DOKKAT_STATE   ADD CONSTRAINT DOKKAT_STATE_PK PRIMARY KEY (DOKKAT_STATE_ID);