ALTER TABLE DOKUMENT_MOTTAK_INFO
	ADD (
    K_KONV_BEHANDLING VARCHAR2(50 CHAR),
    K_ARKIV_BEHANDLING VARCHAR2(50 CHAR),
    K_PREDEFINERT_ARKIV_SYSTEM VARCHAR2(50 CHAR),
    ARKIV_TEMA VARCHAR2(50 CHAR)
);

-- K_KONV_BEHANDLING
CREATE TABLE K_KONV_BEHANDLING (
  K_KONV_BEHANDLING VARCHAR2(50 CHAR)  NOT NULL,
  DEKODE         VARCHAR2(200 CHAR) NOT NULL,
  OPPRETTET_DATO TIMESTAMP          NOT NULL,
  OPPRETTET_AV   VARCHAR2(50 CHAR)  NOT NULL,
  ENDRET_DATO    TIMESTAMP          NULL,
  ENDRET_AV      VARCHAR2(50 CHAR)  NULL,
  CONSTRAINT XPK_KONV_BEHANDLING PRIMARY KEY (K_KONV_BEHANDLING)
);

ALTER TABLE DOKUMENT_MOTTAK_INFO
  ADD CONSTRAINT FK_KONV_BEHANDLING
FOREIGN KEY (K_KONV_BEHANDLING)
REFERENCES K_KONV_BEHANDLING;

INSERT INTO K_KONV_BEHANDLING VALUES ('XML_TO_PDFA', 'xml to PDFA', TIMESTAMP '2017-02-08 10:00:00','Stig Strom', null, null);

-- K_ARKIV_BEHANDLING
CREATE TABLE K_ARKIV_BEHANDLING (
  K_ARKIV_BEHANDLING VARCHAR2(50 CHAR)  NOT NULL,
  DEKODE         VARCHAR2(200 CHAR) NOT NULL,
  OPPRETTET_DATO TIMESTAMP          NOT NULL,
  OPPRETTET_AV   VARCHAR2(50 CHAR)  NOT NULL,
  ENDRET_DATO    TIMESTAMP          NULL,
  ENDRET_AV      VARCHAR2(50 CHAR)  NULL,
  CONSTRAINT XPK_ARKIV_BEHANDLING PRIMARY KEY (K_ARKIV_BEHANDLING)
);

ALTER TABLE DOKUMENT_MOTTAK_INFO
  ADD CONSTRAINT FK_ARKIV_BEHANDLING
FOREIGN KEY (K_ARKIV_BEHANDLING)
REFERENCES K_ARKIV_BEHANDLING;

INSERT INTO K_ARKIV_BEHANDLING VALUES ('ARKIVER_FRA_MOTTAK', 'Arkiver fra mottak', TIMESTAMP '2017-02-08 10:00:00','Stig Strom', null, null);
INSERT INTO K_ARKIV_BEHANDLING VALUES ('MOTTA_UTEN_ARKIVERING', 'Motta uten arkivering', TIMESTAMP '2017-02-08 10:00:00','Stig Strom', null, null);

-- K_ARKIV_SYSTEM
CREATE TABLE K_ARKIV_SYSTEM (
  K_ARKIV_SYSTEM VARCHAR2(50 CHAR)  NOT NULL,
  DEKODE         VARCHAR2(200 CHAR) NOT NULL,
  OPPRETTET_DATO TIMESTAMP          NOT NULL,
  OPPRETTET_AV   VARCHAR2(50 CHAR)  NOT NULL,
  ENDRET_DATO    TIMESTAMP          NULL,
  ENDRET_AV      VARCHAR2(50 CHAR)  NULL,
  CONSTRAINT XPK_ARKIV_SYSTEM PRIMARY KEY (K_ARKIV_SYSTEM)
);

ALTER TABLE DOKUMENT_MOTTAK_INFO
  ADD CONSTRAINT FK_PREDEFARKIVSYSTEM
FOREIGN KEY (K_PREDEFINERT_ARKIV_SYSTEM)
REFERENCES K_ARKIV_SYSTEM;

INSERT INTO K_ARKIV_SYSTEM VALUES ('JOARK', 'Joark', TIMESTAMP '2017-02-08 10:00:00','Stig Strom', null, null);