CREATE TABLE EKSTERN_DOKUMENT_TYPE
(
  ID                        NUMBER(19, 0)      NOT NULL,
  EKSTERN_DOKUMENTTYPE_ID   VARCHAR2(20 CHAR)  NOT NULL,
  K_EKSTERN_ID_TYPE         VARCHAR2(50 CHAR)  NOT NULL,
  FK_DOKUMENTTYPE_INFO      NUMBER(19, 0)      NOT NULL,
  OPPRETTET_AV              VARCHAR2(50 CHAR)  NOT NULL,
  OPPRETTET_DATO            TIMESTAMP          NOT NULL,
  ENDRET_AV                 VARCHAR2(50 CHAR)  NULL,
  ENDRET_DATO               TIMESTAMP          NULL,
  VERSJON                   NUMBER(19, 0)      NOT NULL,
  CONSTRAINT XPK_EKSTERN_DOKUMENT_TYPE PRIMARY KEY (ID)
);

CREATE TABLE K_EKSTERN_ID_TYPE (
  K_EKSTERN_ID_TYPE   VARCHAR2(20 CHAR)  NOT NULL,
  DEKODE              VARCHAR2(200 CHAR) NOT NULL,
  OPPRETTET_AV        VARCHAR2(50 CHAR)  NOT NULL,
  OPPRETTET_DATO      TIMESTAMP          NOT NULL,
  ENDRET_DATO         TIMESTAMP          NULL,
  ENDRET_AV           VARCHAR2(50 CHAR)  NULL,
  CONSTRAINT XPK_EKSTERN_ID_TYPE PRIMARY KEY (K_EKSTERN_ID_TYPE)
);

CREATE SEQUENCE EKSTERN_DOKUMENT_TYPE_SEQ START WITH 100 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;

ALTER TABLE EKSTERN_DOKUMENT_TYPE
  ADD CONSTRAINT FK_DOKUMENTTYPE_EKSTERN
FOREIGN KEY (FK_DOKUMENTTYPE_INFO)
REFERENCES DOKUMENTTYPE_INFO;

ALTER TABLE EKSTERN_DOKUMENT_TYPE
  ADD CONSTRAINT FK_EKSTERN_ID_TYPE
FOREIGN KEY (K_EKSTERN_ID_TYPE)
REFERENCES K_EKSTERN_ID_TYPE;

INSERT INTO K_EKSTERN_ID_TYPE (K_EKSTERN_ID_TYPE, DEKODE, OPPRETTET_AV, OPPRETTET_DATO)
VALUES ('SERVICE_CODE', 'Service code', 'Ragne Henriksen', TIMESTAMP '2017-10-24 10:00:00');