CREATE TABLE SPRAAK_INFO
(
  ID                        NUMBER(19, 0)      NOT NULL,
  SPRAAKLAG                 VARCHAR2(20 CHAR)  NOT NULL,
  FK_DOKUMENTPRODUKSJON_INFO      NUMBER(19, 0)      NOT NULL,
  OPPRETTET_AV              VARCHAR2(50 CHAR)  NOT NULL,
  OPPRETTET_DATO            TIMESTAMP          NOT NULL,
  ENDRET_AV                 VARCHAR2(50 CHAR)  NULL,
  ENDRET_DATO               TIMESTAMP          NULL,
  VERSJON                   NUMBER(19, 0)      NOT NULL,
  CONSTRAINT XPK_SPRAAK_INFO PRIMARY KEY (ID)
);


CREATE SEQUENCE SPRAAK_INFO_SEQ START WITH 100 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;

ALTER TABLE SPRAAK_INFO
  ADD CONSTRAINT FK_SPRAAKINFO_DOKPRODINFO
FOREIGN KEY (FK_DOKUMENTPRODUKSJON_INFO)
REFERENCES DOKUMENT_PRODUKSJON_INFO (ID);

