ALTER TABLE DOKUMENTTYPE_INFO ADD TEMA VARCHAR2(100 CHAR) NULL;
ALTER TABLE DOKUMENTTYPE_INFO ADD BEHANDLINGSTEMA VARCHAR2(100 CHAR) NULL;

ALTER TABLE DOKUMENTTYPE_INFO MODIFY ( SENSITIVT NULL );

INSERT INTO K_EKSTERN_ID_TYPE (K_EKSTERN_ID_TYPE, DEKODE, OPPRETTET_AV, OPPRETTET_DATO)
VALUES ('SED_TYPE', 'SEDtype', 'Ragne Henriksen', TIMESTAMP '2018-02-28 10:00:00');