spring.main.banner-mode=off
logging.config=classpath:logback-spring.xml

# server
server.shutdown=graceful
server.error.include-message=always

#db
spring.jpa.open-in-view=false
spring.transaction.default-timeout=300s
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
spring.jpa.properties.hibernate.session_factory.interceptor=no.nav.dokmet.core.interceptor.ChangeStampInterceptor

# actuators
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus