<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<artifactId>dokmet</artifactId>
		<groupId>no.nav.dokmet</groupId>
		<version>1.0-SNAPSHOT</version>
	</parent>

	<artifactId>app</artifactId>

	<properties>
		<maven.deploy.skip>true</maven.deploy.skip>
	</properties>

	<dependencies>
		<dependency>
			<groupId>no.nav.dokmet</groupId>
			<artifactId>web</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.dokmet</groupId>
			<artifactId>varseladmin-frontend</artifactId>
		</dependency>
		<dependency>
			<groupId>no.nav.dokmet</groupId>
			<artifactId>varseladmin-bff</artifactId>
		</dependency>

		<dependency>
			<groupId>net.logstash.logback</groupId>
			<artifactId>logstash-logback-encoder</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<finalName>app</finalName>
					<excludes>
						<exclude>
							<groupId>org.springframework.boot</groupId>
							<artifactId>spring-boot-configuration-processor</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>