kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: DOKMET_PROXY_HOST
      value: "webproxy.nais"
    - name: DOKMET_PROXY_PORT
      value: "8088"
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{ this }}
           {{/each}}
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{SERVICEUSER_VAULT_PATH}}
        mountPath: "/secrets/serviceuser/dokmet"
      - kvPath: { { DOKMET_DS } }
        mountPath: /var/run/secrets/nais.io/dokmetDS
azure:
  application:
    enabled: true
    claims:
      extra:
        - "azp_name"
  accessPolicy:
    inbound:
      rules:
    {{#each AZURE_IAC_RULES}}
       - application: {{app}}
         namespace: {{namespace}}
         cluster: {{cluster}}
    {{/each}}