spring.main.banner-mode=OFF

# actuators
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus

spring.jpa.properties.hibernate.session_factory.interceptor=no.nav.dokmet.core.interceptor.ChangeStampInterceptor
spring.flyway.table=schema_version