spring.main.banner-mode=off

# server
server.shutdown=graceful
server.error.include-message=always

#db
spring.jpa.open-in-view=false
spring.transaction.default-timeout=300s
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.session_factory.interceptor=no.nav.dokmet.core.interceptor.ChangeStampInterceptor
spring.flyway.table=schema_version
spring.flyway.default-schema=DOKKAT

# actuators
management.endpoints.web.exposure.include=prometheus,health

# store sessions in db
spring.session.store-type=jdbc
spring.session.jdbc.table-name=dokmet.spring_session
spring.session.jdbc.initialize-schema=never