name: Build, deploy dev feature

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  publish-artifact-tmp:
    uses: navikt/dok-workflows/.github/workflows/publish-artifact.yml@main
    with:
      java-version: '17'
    secrets: inherit
  build:
    uses: navikt/dok-workflows/.github/workflows/build-deploy-feature.yml@main
    needs: publish-artifact-tmp
    secrets: inherit
